
version: '3'

services:
  web:
    build: .
    entrypoint: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always     # or "unless-stopped"